# Generated by Django 4.2.1 on 2023-05-27 15:07

from django.db import migrations, models
import employees.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(max_length=10, validators=[employees.web.models.validate_salary], verbose_name='Salary'),
        ),
    ]
